### ISSUE TITLE
我需要的就是这个控件

### ISSUE THREAD

**Issue by chain911** [zhangyuChen1991/PtrSwipeMenuRecyclerView#1]
一直想弄一个下拉上拉侧滑拖拽排序都支持的控件 然后所有的功能都是动态的 用户可代码动态控制打开或者关闭某个功能 我分别结合了https://github.com/jdsjlzx/LRecyclerView和https://github.com/yanzhenjie/SwipeRecyclerView最后都是有冲突导致某个功能没法用 博主的目前下拉刷新和拖拽排序也有冲突

**Comment by zhangyuChen1991** [comment]
你还是要慎用，这个控件还没人去踩过坑，一直没实践过。当时初步写完就没再花功夫维护了。你说的冲突也确实存在的，你看着代码小心着点搞吧，踩坑了别骂我啊...

**Comment by chain911** [comment]
嗯呢 没事 不会骂你。。。
