### ISSUE TITLE
给item 设置点击事件后 。侧滑失效

### ISSUE THREAD

**Issue by lichtz** [zhangyuChen1991/PtrSwipeMenuRecyclerView#2]

**Comment by zhangyuChen1991** [comment]
滑动事件应该是被点击消费掉了    哭脸~  这库闲置好久了   而且最近特别忙，实在抽不出空来维护。真的是 很抱歉，你看看同类型的其他开源吧，    等我抽空，回头来料理它，在这之前，我也不想坑谁呀，相互学习交流用吧。然后，还是很感谢提出的意见！

**Comment by lichtz** [comment]
解决了。。  `
    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {

        switch (ev.getAction()) {

            case MotionEvent.ACTION_MOVE:


                return true;
            case MotionEvent.ACTION_UP:


                break;
        }

        return super.onInterceptTouchEvent(ev);
    }

`

 在SwipeMenuLayout 进行拦截

**Comment by lichtz** [comment]
点击事件 设在contentView 上，就可以了
